### ISSUE TITLE
Cleanup wikipedia/data importance computation scripts

### ISSUE THREAD

**Issue by lonvia** [osm-search/wikipedia-wikidata#1]
The scripts in this repository could do with some cleanup. Currently the import process needs a Postgres database and more than 1TB of disk space. There is room for improvement here. It might even be that we don't need a database at all and can just create a Postgresql dump directly from the Wiki dumps using some clever stream processing.

**Comment by zhenglin-charlie-li** [comment]
Hi, I am looking for some issues to get started, and I found that this issue appears on GSoC project idea lists twice, both in 2021 and 2022:

https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2022/Project_ideas

https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2021/Project_ideas


but when I carefully looked into this issue, I found that this issue was created in 2020 and this repository was updated in 2022.

So I am wondering if this is still an issue that needs to be resolved. If yes, I think the solution may be related to the performance issue with the database; maybe we could utilize some data processing technology to process the data, like Spark or something else.
