### ISSUE TITLE
Investigate importance of 0

### ISSUE THREAD

**Issue by lonvia** [osm-search/wikipedia-wikidata#43]
About 3% of the entries in wikipedia_article currently have an importance of 0. We should investigate when this happens and if this is expected.

Depending on how the values come to be, we have to handle the entries as 'insufficient data' or 'of extremely low importance'. In the first case, the lines can be dropped, int the second case we should keep them.

**Comment by mtmail** [comment]
The formula used is `importance = LOG(totalcount)/LOG((SELECT MAX(totalcount) FROM wikipedia_article_full))`

Any entry (page/article) with totalcount=1 leads to an importance of 0. Mathematically the max(totalcount) can be any number, the result will be 0.

So it's the 'extremely low importance' scenario, affecting 259.504 pages (2817 for language=de).

I think we should add a low default, e.g. 0.00000001, because it's still significant that a title is inside Wikipedia regardless how few other articles link to it.

**Comment by mtmail** [comment]
I belive this no longer an issue

```sql
SELECT min(importance), max(importance) FROM wikimedia_importance;
  min  | max
-------+-----
 1e-10 |   1
```
