### ISSUE TITLE
Filter non-earth coordinates

### ISSUE THREAD

**Issue by mtmail** [osm-search/wikipedia-wikidata#6]
E.g. https://en.wikipedia.org/wiki/Huygens_(crater)

The coordinates on other planets have no use to Nominatim.

**Comment by SachitSankhe** [comment]
Hi, I want to contribute ,so can I know if this issue is still up for grabs? And if yes what can help me get started to resolve this as I am doing this for the first time. I understand that we do not require coordinates that have latitude out of the range of -90 to 90 and longitude out of the range of -180 to 180 and also they should be like (41.40339°N,2.174028°E) and not like (304.42°W 13.88°S) that is they should be in (some-value)degree N and (some-value)degree S. Have I understood it correctly?

**Comment by mtmail** [comment]
Wikipedia contains coordinates on other planets. E.g. the URLs on https://en.wikipedia.org/wiki/List_of_rovers_on_extraterrestrial_bodies contain "globe:mars" and clicking goes to a Mars map. It's a tiny tiny fraction of places in Wikipedia and likely doesn't affect the output of the script.

https://github.com/osm-search/Nominatim/labels has several issues marked 'help wanted', 'good first issue' and 'test needed'.

**Comment by mtmail** [comment]
The table `geo_tags` has the columns

```
# CREATE TABLE `geo_tags` (
#   `gt_id`      int(10) unsigned NOT NULL AUTO_INCREMENT,
#   `gt_page_id` int(10) unsigned NOT NULL,
#   `gt_globe`   varbinary(32)    NOT NULL,
#   `gt_primary` tinyint(1)       NOT NULL,
#   `gt_lat`     decimal(11,8)              DEFAULT NULL,
#   `gt_lon`     decimal(11,8)              DEFAULT NULL,
#   `gt_dim`     int(11)                    DEFAULT NULL,
#   `gt_type`    varbinary(32)              DEFAULT NULL,
#   `gt_name`    varbinary(255)             DEFAULT NULL,
#   `gt_country` binary(2)                  DEFAULT NULL,
#   `gt_region`  varbinary(3)               DEFAULT NULL,
```

In order to filter you have to make sure the value in `gt_globe` column is `earth`.

Checking the latitude and longitude ranges is also a good idea.

**Comment by SachitSankhe** [comment]
OK, thanks for the help.

**Comment by mtmail** [comment]
This is fixed on the https://github.com/osm-search/wikipedia-wikidata/pull/13 branch, not not on the master branch yet.

**Comment by mtmail** [comment]
Been fixed in `wikidata_process.sh` and separately `wikidata_sql2csv.sh`.
